spring:
  application:
    name: EventGo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: VeoGlo24!!
    url: jdbc:mysql://localhost:3306/sbm_db
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  upload:
    dir: file:./src/main/resources/static/images/
